let timelineElements = [
  {
    id: 1,
    title: "FullStack Developer",
    location: "KAMPANA DIGITAL",
    description: "Desenvolvimento de sistemas Web, Construção de APIs, Integração entre sistemas ecommerce (OpenCart, Nuvemshop, Shopify, Tray, entre outros) e RD Station (assim como sistemas CRM), Implementação de sistemas de pagamento para sistemas Web (utilizado conta teste – sandbox ASAAS) configuração de Servidores de Aplicação, Gerenciamento de Banco de Dados, levantamento de Requisitos e Construção de Telas (UI/UX), Configuração de ferramentas da AWS (EC2, RDS, VPC, entre outros), Desenvolvimento de Dashboards de Indicadores com ênfase em análise de Bis (Power BI).",
    //buttonText: "Visitar Website",
    date: "Abril 2020 - Presente",
    icon: "work",
  },
  {
    id: 2,
    title: "Next Level Week (Full Stack)",
    location: "ROCKETSEAT",
    description: "Desenvolvimento de uma sistema completo, usando para backend(nodeJs), banco de dados(mysql), frontend(reactJs), , mobile(react-native).",
    //buttonText: "Visitar Website",
    date: "Concluído em 2020",
    icon: "school",
  },
  {
    id: 3,
    title: "Estagiário Gestão de Projetos",
    location: "ENEL GOIÁS",
    description: "Gerenciamento e desenvolvimento de projetos internos. Controle de incidentes e monitoramento de chamados, fazendo tratativa preventivas através de testes nos sistemas implementados. Participação em processos de desenvolvimento e atualização de versões dos sistemas internos, assim como etapas de homologação até o processo de produção. Desenvolvimento de um sistema em Python para automatização de um processo de consulta em banco e exportação em massa.",
    //buttonText: "Visitar Website",
    date: "Julho 2019 - Abriu 2020",
    icon: "work",
  },
  {
    id: 4,
    title: "Curso de Power BI - Nivel Intermediário",
    location: "PLANILHEIROS",
    description: "Curso de nível de Power BI, onde pude aprender as principais ferramentas do Power BI para não só criar dashboards e relatórios dinâmicos, mas também conseguir analisar milhares de informações de forma simples e intuitiva. Nesse curso consolidei meu conhecimento nas mais diversas ferramentas para usar todo o potencial do Business Intelligence para criar relatórios intuitivos e impressionantes, com gráficos, indicadores, entre outros.",
    //buttonText: "Visitar Website",
    date: "Concluído em 2019",
    icon: "school",
  },
  {
    id: 5,
    title: "Semana Omnistack (Full Stack)",
    location: "ROCKETSEAT",
    description: "Desenvolvimento de uma sistema completo, usando para backend(nodeJs), banco de dados(mondoDB), frontend(reactJs), mobile(react-native).",
    //buttonText: "Visitar Website",
    date: "Concluído em 2019",
    icon: "school",
  },
  {
    id: 6,
    title: "Curso de Python - Nível Intermediário",
    location: "UDEMY",
    description: "",
    //buttonText: "Visitar Website",
    date: "Concluído em 2019",
    icon: "school",
  },
  {
    id: 7,
    title: "Etagiário em TI/Suporte",
    location: "PACTO SOFTWARE E GESTÃO",
    description: "Prestar suporte presencial e a distância aos usuários do sistema corporativo. Gerenciamento de dados cadastrais dos usuários nos sistemas internos da empresa. Desenvolvimento de um sistema de indicadores (Dashboard) para análise e gestão de chamados.",
    //buttonText: "Visitar Website",
    date: "Março 2017 - Julho 2019",
    icon: "work",
  },
  {
    id: 8,
    title: "Curso de Inglês - Nível Intermediário",
    location: "PRONATEC - IFG",
    description: "",
    //buttonText: "Visitar Website",
    date: "Março 2017 - Julho 2019",
    icon: "school",
  },
  {
    id: 9,
    title: "Desenvolvimento projeto Miniempresas",
    location: "INSTITUTO FEDERAL DE GOIÁS",
    description: "",
    //buttonText: "Visitar Website",
    date: "Concluído em 2014",
    icon: "school",
  },
  {
    id: 10,
    title: "Técnico Integrado em Edificações",
    location: "INSTITUTO FEDERAL DE GOIÁS",
    description: "",
    //buttonText: "Visitar Website",
    date: "2012 - 2015",
    icon: "school",
  }
];

export default timelineElements;
